ingredients=Felce,Mandragora,Artiglio,Fiore,Fungo,Rospo,Piuma,Scorpione

formula.0.RED.size=BIG
formula.0.RED.sign=POSITIVE
formula.0.GREEN.size=BIG
formula.0.GREEN.sign=POSITIVE
formula.0.BLUE.size=BIG
formula.0.BLUE.sign=POSITIVE

formula.1.RED.size=BIG
formula.1.RED.sign=NEGATIVE
formula.1.GREEN.size=BIG
formula.1.GREEN.sign=NEGATIVE
formula.1.BLUE.size=BIG
formula.1.BLUE.sign=NEGATIVE

formula.2.RED.size=SMALL
formula.2.RED.sign=NEGATIVE
formula.2.GREEN.size=SMALL
formula.2.GREEN.sign=POSITIVE
formula.2.BLUE.size=BIG
formula.2.BLUE.sign=NEGATIVE

formula.3.RED.size=SMALL
formula.3.RED.sign=POSITIVE
formula.3.GREEN.size=SMALL
formula.3.GREEN.sign=NEGATIVE
formula.3.BLUE.size=BIG
formula.3.BLUE.sign=POSITIVE

formula.4.RED.size=SMALL
formula.4.RED.sign=NEGATIVE
formula.4.GREEN.size=BIG
formula.4.GREEN.sign=POSITIVE
formula.4.BLUE.size=SMALL
formula.4.BLUE.sign=POSITIVE

formula.5.RED.size=SMALL
formula.5.RED.sign=POSITIVE
formula.5.GREEN.size=BIG
formula.5.GREEN.sign=NEGATIVE
formula.5.BLUE.size=SMALL
formula.5.BLUE.sign=NEGATIVE

formula.6.RED.size=BIG
formula.6.RED.sign=POSITIVE
formula.6.GREEN.size=SMALL
formula.6.GREEN.sign=POSITIVE
formula.6.BLUE.size=SMALL
formula.6.BLUE.sign=NEGATIVE

formula.7.RED.size=BIG
formula.7.RED.sign=NEGATIVE
formula.7.GREEN.size=SMALL
formula.7.GREEN.sign=NEGATIVE
formula.7.BLUE.size=BIG
formula.7.BLUE.sign=POSITIVE

formula.count=8

targetStudentId=student-1
targetSelfId=self
startingGold=5
startingReputation=10
